FROM ubuntu:latest
LABEL "Author"="hasnexus"
LABEL "Project"="vora-bold"
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y
RUN apt-get update && apt-get install -y wget unzip apache2
RUN wget https://www.tooplate.com/zip-templates/2161_vora_bold.zip
RUN unzip 2161_vora_bold.zip
RUN cp -r 2161_vora_bold/* /var/www/html/
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
EXPOSE 80